Test.zz_exit called, as it should
